#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

$SCREENSHOT
magick $PICTURE -blur $BLUR $PICTURE
# Add keyboard layout
i3lock -i $PICTURE --keylayout 1
rm $PICTURE
