general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot # или укажи путь к картинке, например /home/as/wallpaper.png
    color = rgba(0, 0, 0, 1.0)
    blur_passes = 2 # 0, если хочешь чистый черный цвет без размытия фона
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(127, 63, 191) # Твой 7f3fbf
    inner_color = rgb(0, 0, 0)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

# Тот самый индикатор раскладки
label {
    monitor =
    text = $LAYOUT
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = Inter # или твой любимый шрифт
    position = 0, 80
    halign = center
    valign = center
}
